version: '3.8'
services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/java_react
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DB_AUTO_COMMIT: false
      HIBERNATE_DDL: update
      SHOW_SQL: true
      HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      FRONTEND_URL: http://localhost:8091/
    depends_on:
      - postgres
    networks:     ## BUNLARA DA GEREK YOK ASLINDA. SADECE BACKEND'IN POSTGRES CONTAINER'I ILE AYNI AGDA OLMASI YETERLI.
      network-swe212:


  frontend:
    build:
      context: ./Frontend
      args:
        - VITE_APP_BACKEND_URL=http://localhost:8090  # NO NEED FOR THIS BUT KEEP IT FOR NOW
    container_name: frontend
    ports:
      - "8091:80"
    depends_on:
      - backend
    networks:
      network-swe212:


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: java_react
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      network-swe212:



volumes:
  pgdata:

networks:
  network-swe212:
