const isMobile = window.innerWidth <= 768;
const styles = {
    container: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh",
        width: "100vw",
        margin: 0,
        padding: isMobile ? "10px" : "20px",
        background: "linear-gradient(135deg, #e0e7ff 0%, #f4f7fc 100%)",
        overflow: "hidden",
        boxSizing: "border-box",
    },
    formContainer: {
        width: isMobile ? "90%" : "100%",
        maxWidth: isMobile ? "none" : "400px",
        padding: isMobile ? "15px" : "30px",
        backgroundColor: "#ffffff",
        borderRadius: "12px",
        boxShadow: "0 8px 24px rgba(0, 0, 0, 0.08)",
        textAlign: "center",
        animation: "fadeIn 0.5s ease-in-out",
        boxSizing: "border-box",
    },
    header: {
        fontSize: isMobile ? "22px" : "28px",
        color: "#1a202c",
        marginBottom: isMobile ? "15px" : "20px",
        fontWeight: "700",
        fontFamily: "'Inter', sans-serif",
    },
    errorMessage: {
        color: "#f56565",
        fontSize: isMobile ? "12px" : "13px",
        marginBottom: isMobile ? "10px" : "15px",
        fontWeight: "500",
        backgroundColor: "#fff5f5",
        padding: "8px",
        borderRadius: "6px",
    },
    form: {
        display: "flex",
        flexDirection: "column",
    },
    inputGroup: {
        marginBottom: isMobile ? "12px" : "16px",
        textAlign: "left",
    },
    label: {
        fontSize: isMobile ? "12px" : "14px",
        color: "#4a5568",
        marginBottom: "8px",
        fontWeight: "600",
        fontFamily: "'Inter', sans-serif",
    },
    input: {
        padding: isMobile ? "10px 12px" : "12px 14px",
        fontSize: isMobile ? "13px" : "15px",
        color: "#2d3748",
        backgroundColor: "#f7fafc",
        border: "1px solid #e2e8f0",
        borderRadius: "8px",
        width: "100%",
        transition: "all 0.3s ease",
        fontFamily: "'Inter', sans-serif",
        boxSizing: "border-box",
    },
    inputFocus: {
        outline: "none",
        borderColor: "#5a67d8",
        boxShadow: "0 0 0 3px rgba(90, 103, 216, 0.2)",
        backgroundColor: "#ffffff",
    },
    button: {
        padding: isMobile ? "10px" : "14px",
        backgroundColor: "#5a67d8",
        color: "#ffffff",
        fontSize: isMobile ? "13px" : "15px",
        fontWeight: "600",
        border: "none",
        borderRadius: "8px",
        cursor: "pointer",
        transition: "all 0.3s ease",
        fontFamily: "'Inter', sans-serif",
        marginTop: isMobile ? "5px" : "8px",
    },
    buttonHover: {
        backgroundColor: "#4c51bf",
        transform: "translateY(-2px)",
        boxShadow: "0 4px 12px rgba(90, 103, 216, 0.3)",
    },
    buttonActive: {
        transform: "translateY(0)",
        boxShadow: "none",
    },
    secondaryButton: {
        padding: isMobile ? "10px" : "14px",
        backgroundColor: "transparent",
        color: "#5a67d8",
        fontSize: isMobile ? "13px" : "15px",
        fontWeight: "600",
        border: "1px solid #5a67d8",
        borderRadius: "8px",
        cursor: "pointer",
        transition: "all 0.3s ease",
        fontFamily: "'Inter', sans-serif",
        marginTop: isMobile ? "8px" : "12px",
    },
    secondaryButtonHover: {
        backgroundColor: "#5a67d8",
        color: "#ffffff",
        transform: "translateY(-2px)",
        boxShadow: "0 4px 12px rgba(90, 103, 216, 0.3)",
    },
    secondaryButtonActive: {
        transform: "translateY(0)",
        boxShadow: "none",
    },
};

export default styles;